#spring:
#  security:
#    oauth2:
#      client:
#        provider:
#          azure:
#            authorization-uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
#            token-uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
#            jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
#        registration:
#          azure:
#            provider: azure
#            client-id: 7db2e2c1-a094-4e25-be0b-36ca18094c9c
#            client-secret: 5928Q~1aMVNZlk3zubTMf1S1H4-y3R-uaDXYnc~s
#            authorization-grant-type: authorization_code
#            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
#            scope: openid

#  cloud:
#    azure:
#      active-directory:
#        user-group:
#          allowed-group-names:
#          -         
